# Repository settings managed through configuration as code
# Enforces status checks so failing builds block merges
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - CI
